version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
image: Visual Studio 2017
shallow_clone: true
platform: x64
build_script:
- gradlew.bat deploy
after_test:
- ps: ls $env:appveyor_build_folder\releases\release-*\bundles\
artifacts:
- path: releases\release-*\bundles\TokenTool-*.exe
  name: TokenTool-Install
- path: releases\release-*\TokenTool-*.jar
  name: TokenTool-Jar
deploy:
- provider: GitHub
  description: Windows release from AppVeyor
  tag: $(env:appveyor_repo_tag_name)
  auth_token:
    secure: HXIHe/F7K2yGOZ0I56DW5PevrQDe+zjyunjORGKYaUGxFtvPYPcmOdjZT69tzHcS
  artifact: TokenTool-Install, TokenTool-Jar
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#development'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true